services:
  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/monitoring/prometheus.yml'
    volumes:
      - ./monitoring/prometheus.yml:/etc/monitoring/prometheus.yml:ro
    restart: unless-stopped
    ports:
      - "9090:9090"
    depends_on:
      - cadvisor

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/rootfs/var/lib/docker/:ro
    privileged: true
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  grafana_data: {}
  prom_data: {}
